variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

stages:
  - pages
  - quality
  - tests

.install-deps-template: &install-deps
  before_script:
      - pip install poetry
      - poetry --version
      - poetry config virtualenvs.in-project true
      - poetry install -vv

.quality-template: &quality 
  <<: *install-deps
  image: python:3.6
  stage: quality

.test-template: &test 
  <<: *install-deps
  stage: tests
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script: 
    - poetry run pytest --cov=automatic_testing tests/ 
    - poetry run coverage-badge

  artifacts:
      paths:
          - tests/logs

      when: always
      expire_in: 1 week

# Quality jobs ----------------------

check-bandit:
  <<: *quality
  script: poetry run bandit .

check-black:
  <<: *quality
  script: poetry run black .

# check-flake8:
#   <<: *quality
#   script: poetry run flake8 ./automatic_testing

check-isort:
  <<: *quality
  script: poetry run isort .

# Tests jobs ------------------------

python3.6:
  <<: *test
  image: python:3.6

python3.7:
  <<: *test
  image: python:3.7

python3.8:
  <<: *test
  image: python:3.8


# Documentation ---------------------
# this stage has to be called `pages` if we want gitalb to host the docs for us
pages: 
  <<: *install-deps
  image: python:3.8 
  stage: pages
  script:
      - cd docs && poetry run sphinx-build -b html . ../public
  artifacts:
    paths:
        - public
  only:
    - master
